workflows:
  flutter-ci:
    name: Flutter CI
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "submission_2"
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Clean Flutter Cache
        script: flutter clean
      - name: Analyze
        script: flutter analyze
      - name: Run unit tests (core module)
        script: |                  
          cd core
          flutter pub get
          flutter test
      - name: Run unit tests (movies module)
        script: flutter test movies/test
      - name: Run unit tests (tv series module)
        script: flutter test tv_series/test
      - name: Run Integration Tests
        script: flutter drive --target=test_driver/integration_test.dart
      - name: Build APK with Flutter
        script: flutter build apk --debug
      - name: Run Integration Tests
        script: flutter drive --target=integration_test/app_test.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-*.apk