workflows:
  flutter-ci:
    name: Flutter CI
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Clean Flutter Cache
        script: flutter clean
      - name: Analyze
        script: flutter analyze
      - name: Run integration tests
        script: flutter test integration_test
      - name: Run unit tests (movies module)
        script: flutter test movies/test
    artifacts:
      - build/app/outputs/flutter-apk/app-*.apk