// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtnNr5MRiFvnjZbNp8BhbARGn8JhAqu4',
    appId: '1:662744895242:web:547b72c8bc076ac83df4f3',
    messagingSenderId: '662744895242',
    projectId: 'movieflutter-a08ca',
    authDomain: 'movieflutter-a08ca.firebaseapp.com',
    storageBucket: 'movieflutter-a08ca.firebasestorage.app',
    measurementId: 'G-240E9THJ01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqj-Pb6_1XFxgdQ2OOeGexggfXaMCVeI',
    appId: '1:662744895242:android:f84a03013d832d583df4f3',
    messagingSenderId: '662744895242',
    projectId: 'movieflutter-a08ca',
    storageBucket: 'movieflutter-a08ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuv2XTGRLIwg1BDpBIyFvhwksQkKGSHm8',
    appId: '1:662744895242:ios:ba8e9be6d36fdc5b3df4f3',
    messagingSenderId: '662744895242',
    projectId: 'movieflutter-a08ca',
    storageBucket: 'movieflutter-a08ca.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
