name: movies
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage: https://github.com/atifa1110/Movie-Flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tv_series:
    path: ../tv_series

  core:
    path: ../core

  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  rxdart: ^0.27.7
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  bloc_test: ^9.1.4
  mocktail: ^0.3.0
  test_cov_console: ^0.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


