// Mocks generated by Mockito 5.4.4 from annotations
// in tv_series/test/helper/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/data/datasources/tv_series_local_data_source.dart' as _i11;
import 'package:core/data/datasources/tv_series_remote_data_source.dart' as _i9;
import 'package:core/data/models/tv_series_detail_model.dart' as _i3;
import 'package:core/data/models/tv_series_model.dart' as _i10;
import 'package:core/data/models/tv_series_table.dart' as _i12;
import 'package:core/domain/entities/tv_series.dart' as _i7;
import 'package:core/domain/entities/tv_series_detail.dart' as _i8;
import 'package:core/domain/repositories/tv_series_repository.dart' as _i4;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i4.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>
      getNowPlayingTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingTvSeries,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                    _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
              this,
              Invocation.method(
                #getNowPlayingTvSeries,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                    _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                    _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>> searchTvSeries(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [query],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [query],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.TvSeriesDetail>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i8.TvSeriesDetail>>.value(
                _FakeEither_0<_i6.Failure, _i8.TvSeriesDetail>(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i8.TvSeriesDetail>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesRecommendations,
              [id],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                    _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
              this,
              Invocation.method(
                #getTvSeriesRecommendations,
                [id],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveWatchlist(
          _i8.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tvSeries],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeWatchlist(
          _i8.TvSeriesDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistTvSeries,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                    _FakeEither_0<_i6.Failure, List<_i7.TvSeries>>(
              this,
              Invocation.method(
                #getWatchlistTvSeries,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i9.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i10.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTvSeries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i10.TvSeriesModel>>.value(<_i10.TvSeriesModel>[]),
      ) as _i5.Future<List<_i10.TvSeriesModel>>);

  @override
  _i5.Future<List<_i10.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i10.TvSeriesModel>>.value(<_i10.TvSeriesModel>[]),
      ) as _i5.Future<List<_i10.TvSeriesModel>>);

  @override
  _i5.Future<List<_i10.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i10.TvSeriesModel>>.value(<_i10.TvSeriesModel>[]),
      ) as _i5.Future<List<_i10.TvSeriesModel>>);

  @override
  _i5.Future<List<_i10.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [query],
        ),
        returnValue:
            _i5.Future<List<_i10.TvSeriesModel>>.value(<_i10.TvSeriesModel>[]),
      ) as _i5.Future<List<_i10.TvSeriesModel>>);

  @override
  _i5.Future<_i3.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i5.Future<_i3.TvSeriesDetailResponse>.value(
            _FakeTvSeriesDetailResponse_1(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.TvSeriesDetailResponse>);

  @override
  _i5.Future<List<_i10.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendations,
          [id],
        ),
        returnValue:
            _i5.Future<List<_i10.TvSeriesModel>>.value(<_i10.TvSeriesModel>[]),
      ) as _i5.Future<List<_i10.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i11.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i12.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tvSeries],
        ),
        returnValue: _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> removeWatchlist(_i12.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tvSeries],
        ),
        returnValue: _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i12.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [id],
        ),
        returnValue: _i5.Future<_i12.TvSeriesTable?>.value(),
      ) as _i5.Future<_i12.TvSeriesTable?>);

  @override
  _i5.Future<List<_i12.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i12.TvSeriesTable>>.value(<_i12.TvSeriesTable>[]),
      ) as _i5.Future<List<_i12.TvSeriesTable>>);
}
